apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: pihole
  namespace: kube-system
spec:
  chart: pihole
  repo: https://mojo2600.github.io/pihole-kubernetes/
  targetNamespace: default
  # We inline configuration options for the Helm chart under valuesContent.
  # This acts as the link to our declarative values.
  valuesContent: |
    admin:
      enabled: true
      existingSecret: "pihole-admin"
      passwordKey: "password"
    DNS1: "127.0.0.1#5335"
    DNS2: ""
    serviceDns:
      type: LoadBalancer
      port: 53
    serviceWeb:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - pihole.homelab
      path: /

    extraEnvVars:
      TZ: "Asia/Kolkata"
      DNSMASQ_LISTENING: "all"
    image:
      repository: pihole/pihole
      tag: "2024.07.0"
    probes:
      liveness:
        type: httpGet
        port: http
        scheme: HTTP
      readiness:
        type: httpGet
        port: http
        scheme: HTTP
    persistentVolumeClaim:
      enabled: true
      storageClass: "local-path"
      size: 5Gi
    dnsmasq:
      persistentVolumeClaim:
        enabled: true
        storageClass: "local-path"
        size: 2Gi
    extraContainers:
      - name: unbound
        image: docker.io/mvance/unbound:latest
        ports:
          - containerPort: 5335
            name: dns-udp
            protocol: UDP
          - containerPort: 5335
            name: dns-tcp
            protocol: TCP
        volumeMounts:
          - name: unbound-config-volume
            mountPath: /opt/unbound/etc/unbound/unbound.conf
            subPath: unbound.conf
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
    extraVolumes:
      - name: unbound-config-volume
        configMap:
          name: unbound-config
