apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: pihole
  namespace: kube-system
spec:
  chart: pihole
  repo: https://mojo2600.github.io/pihole-kubernetes/
  targetNamespace: default
  # We inline configuration options for the Helm chart under valuesContent.
  # This acts as the link to our declarative values.
  valuesContent: |
    admin:
      enabled: true
      existingSecret: "pihole-admin"
      passwordKey: "password"
    DNS1: "unbound.default.svc.cluster.local"
    DNS2: ""
    serviceDns:
      type: LoadBalancer
      port: 53
    serviceWeb:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - pihole.homelab
      path: /

    extraEnvVars:
      TZ: "Asia/Kolkata"
      FTLCONF_dns_listeningMode: "all"
    persistentVolumeClaim:
      enabled: true
      storageClass: "local-path"
      size: 5Gi
    dnsmasq:
      persistentVolumeClaim:
        enabled: true
        storageClass: "local-path"
        size: 2Gi
