apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mojo2600
  namespace: flux-system
spec:
  interval: 2h
  url: https://mojo2600.github.io/pihole-kubernetes/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    admin:
      enabled: true
      existingSecret: "pihole-admin"
      passwordKey: "password"
    DNS1: "127.0.0.1#5335"
    DNS2: ""
    serviceDns:
      type: LoadBalancer
      port: 53
    serviceWeb:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - pihole.homelab
        - ${host_ip}
      path: /
    extraEnvVars:
      TZ: "Asia/Kolkata"
      DNSMASQ_LISTENING: "all"
    image:
      repository: pihole/pihole
      tag: "2024.07.0"
    probes:
      liveness:
        type: httpGet
        port: http
        scheme: HTTP
      readiness:
        type: httpGet
        port: http
        scheme: HTTP
    persistentVolumeClaim:
      enabled: true
      storageClass: "local-path"
      size: 5Gi
    dnsmasq:
      customDnsEntries:
        - address=/pihole.homelab/${host_ip}
        - address=/homeassistant.homelab/${host_ip}
      persistentVolumeClaim:
        enabled: true
        storageClass: "local-path"
        size: 2Gi
    extraContainers:
      - name: unbound
        image: docker.io/mvance/unbound:latest
        ports:
          - containerPort: 5335
            name: unbound-udp
            protocol: UDP
          - containerPort: 5335
            name: unbound-tcp
            protocol: TCP
        volumeMounts:
          - name: unbound-config-volume
            mountPath: /opt/unbound/etc/unbound/unbound.conf
            subPath: unbound.conf
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
    extraVolumes:
      - name: unbound-config-volume
        configMap:
          name: unbound-config
