apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  namespace: default
  labels:
    app: unbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
        - name: unbound
          image: docker.io/mvance/unbound:latest
          ports:
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: config-volume
              mountPath: /opt/unbound/etc/unbound/unbound.conf
              subPath: unbound.conf
      volumes:
        - name: config-volume
          configMap:
            name: unbound-config
---
apiVersion: v1
kind: Service
metadata:
  name: unbound
  namespace: default
spec:
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
  selector:
    app: unbound
  type: ClusterIP
